name: myconda-env
channels:
  - conda-forge
dependencies:
  - python=3.10.13  
  - scikit-learn=1.5.2
  - numpy=1.23.5
  - joblib=1.4.2
  - pip:
    - azureml-defaults==1.59.0
    - azureml-core==1.59.0.post1